### PR TITLE
Allow react 18 in peerDependencies

### PR DESCRIPTION
**Pull request by chentsulin**
React 18 has been officially released: https://reactjs.org/blog/2022/03/29/react-v18.html

### CODE REVIEW

**Comment by chentsulin** [comment]
@t49tran Could you take a look?

**Comment by ulwlu** [comment]
hope this gets merged soon

**Review by a-h-i — APPROVED** [review]

**Comment by samuelgoldenbaum** [comment]
Guys, can we get this merged, please. Holding up production. Thanks

**Comment by bhbs** [comment]
With respect for this library,
I have created a new package for React version 18. Try it out!
https://www.npmjs.com/package/react-google-recaptcha-hook

**Review by t49tran — APPROVED** [review]

**Comment by t49tran** [comment]
This has been merged and released in v1.9.8. Sorry for the delay, I  have traveled recently and didn't have access to github.

**Pull request merged**
