### PR TITLE
effect infinite loop fix

### PR DESCRIPTION
**Pull request by csorfab**
This PR fixes an issue where a new token is requested every time the Provider rerenders.

### CODE REVIEW

**Comment by t49tran** [comment]
Hi @csorfab , what is the scenario when you don't want to request a new token when the Provider is rerendering ? It makes completely sense to me that if there is any change to the Provider then the GoogleRecaptcha component should request a new token.

**Comment by t49tran** [comment]
From what I have seen, there should only be two scenarios when infinite loop can be triggered:

- Putting the Provider and the GoogleRecaptcha component inside the same component (which is not recommended and not how the Provider is written to work).
- Passing inline function or function that is not memoized to GoogleRecaptcha (which has already been covered in the doc).

Can you please provide your scenario / code that leads to infinite loop ?

Regarding a new context object is being returned whenever the Provider is re-rendered, it's sensible to me. If there are changes to the Provider props or it's re-rendered because its parent is re-rendered, it should always return a new context object. It the safest way to guarantee that you always have the up-to-date version of the context.

**Comment by csorfab** [comment]
Hi @t49tran, thanks for your detailed response.

Yes, the infinite loop occured in the first scenario you described, where I had the provider and the token state in the same component. I wanted to use Reacaptcha in only one of my pages, so it didn't make much sense for me to put the Provider in my _app.tsx (I'm using next.js), and I didn't want to have my page in two nested components instead of a single component just because of how this package works.

I don't believe a simple rerender of the Provider with no props changed should trigger a new captcha request event, but I would be interested in a scenario where this is a desirable and expected behavior. Looking at the code again, now I see that my PR would break functionality in a scenario where the Provider props **do** change, I haven't considered that, and I don't see how that could be solved without some heavier refactoring. I think I'll just close this PR for the time being.

Honestly, I just think that a Provider-Consumer architecure for a simple utility lib like this is over-engineering, and it would've introduced unnecessary complexity in my codebase. I ended up writing a simple hook that provides the same functionality without the need of component nesting.

Anyway, thanks for taking the time to tend to this PR! Cheers!

**Comment by joe-akers-douglas-otm** [comment]
> Hi @t49tran, thanks for your detailed response.
> 
> Yes, the infinite loop occured in the first scenario you described, where I had the provider and the token state in the same component. I wanted to use Reacaptcha in only one of my pages, so it didn't make much sense for me to put the Provider in my _app.tsx (I'm using next.js), and I didn't want to have my page in two nested components instead of a single component just because of how this package works.
> 
> I don't believe a simple rerender of the Provider with no props changed should trigger a new captcha request event, but I would be interested in a scenario where this is a desirable and expected behavior. Looking at the code again, now I see that my PR would break functionality in a scenario where the Provider props **do** change, I haven't considered that, and I don't see how that could be solved without some heavier refactoring. I think I'll just close this PR for the time being.
> 
> Honestly, I just think that a Provider-Consumer architecure for a simple utility lib like this is over-engineering, and it would've introduced unnecessary complexity in my codebase. I ended up writing a simple hook that provides the same functionality without the need of component nesting.
> 
> Anyway, thanks for taking the time to tend to this PR! Cheers!

Hey @csorfab would you mind sharing how you overcame this problem - I'm facing the same issue; need recaptcha on a single page in our app and don't want to wrap the whole app with the provider or have nested components for the recaptcha.

**Pull request closed without merging**
